"""D1 schema emission.

Table DDL is read from the source catalog's `sqlite_master` (so the D1
schema is the POST-migration shape 1:1, e.g. `law_versions.date_uncertain`
from migration 004) rather than re-derived from `index.catalog.SCHEMA`.
`provisions` and its indexes are excluded per spec (article text moves to
R2). Both FTS tables (`laws_fts` title-only + `articles_fts` per-segment,
migration 005 / FR-032) are re-declared verbatim (spec v2.0: identical
declaration — the cf-worker copies MATCH SQL from index/fts.py, so column
positions must not drift) and repopulated via INSERTs — the raw
`laws_fts_%`/`articles_fts_%` shadow tables are never carried, so D1 owns
clean FTS indexes.
"""

from __future__ import annotations

import re
import sqlite3

# Tables copied 1:1 from catalog.db (spec §D1). Order matters for
# deterministic output and for FK-style readability (laws first).
COPIED_TABLES: tuple[str, ...] = (
    "laws", "law_versions", "amendments", "schema_version")

# Indexes used by the Worker's list/history/name-resolution queries:
#   idx_versions_date    — version_at_date / list_laws MIN-MAX join
#   idx_amendments_target — law_history / amendments_in_period
# idx_provisions_* deliberately NOT carried (no provisions table in D1).
COPIED_INDEXES: tuple[str, ...] = ("idx_versions_date",
                                   "idx_amendments_target")

# Spec v2.0: IDENTICAL declarations to index/migrations.py migration 005
# (IF NOT EXISTS added for re-runnable schema imports; the fts5(...)
# argument list is verbatim).
LAWS_FTS_DDL = """\
CREATE VIRTUAL TABLE IF NOT EXISTS laws_fts USING fts5(
    law_id UNINDEXED,
    title,
    category UNINDEXED,
    tokenize='unicode61 remove_diacritics 2'
);"""

ARTICLES_FTS_DDL = """\
CREATE VIRTUAL TABLE IF NOT EXISTS articles_fts USING fts5(
    law_id UNINDEXED,
    seg_no UNINDEXED,
    kind UNINDEXED,
    label UNINDEXED,
    body,
    category UNINDEXED,
    tokenize='unicode61 remove_diacritics 2'
);"""

_CREATE_TABLE_RE = re.compile(r"^CREATE TABLE\s+", re.IGNORECASE)
_CREATE_INDEX_RE = re.compile(r"^CREATE INDEX\s+", re.IGNORECASE)


def _idempotent(sql: str, kind_re: re.Pattern, kind: str) -> str:
    """Normalize a sqlite_master DDL string to `CREATE {kind} IF NOT
    EXISTS ...` (sqlite_master strips the clause when the original DDL
    had it; D1 imports are simpler when re-runnable)."""
    if re.match(rf"^CREATE {kind} IF NOT EXISTS\s", sql, re.IGNORECASE):
        return sql
    return kind_re.sub(f"CREATE {kind} IF NOT EXISTS ", sql, count=1)


def _master_sql(conn: sqlite3.Connection, type_: str, name: str) -> str:
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type = ? AND name = ?",
        (type_, name)).fetchone()
    if row is None or row[0] is None:
        raise ValueError(f"{type_} {name!r} not found in source catalog — "
                         "is the db migrated? (run python -m index.build)")
    return row[0]


def d1_schema_sql(conn: sqlite3.Connection) -> str:
    """Emit the full D1 schema (tables + indexes + both FTS tables) as
    one SQL string, terminated statements, deterministic order."""
    parts: list[str] = [
        "-- legalize-bg D1 schema (generated by export_cf; spec "
        "docs/api/cf-data-plane-spec.md v2.0)",
    ]
    for table in COPIED_TABLES:
        sql = _master_sql(conn, "table", table)
        parts.append(_idempotent(sql, _CREATE_TABLE_RE, "TABLE") + ";")
    for index in COPIED_INDEXES:
        sql = _master_sql(conn, "index", index)
        parts.append(_idempotent(sql, _CREATE_INDEX_RE, "INDEX") + ";")
    parts.append(LAWS_FTS_DDL)
    parts.append(ARTICLES_FTS_DDL)
    return "\n\n".join(parts) + "\n"
